version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: myapp-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: myapp-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
